# -*- coding: utf-8 -*-
"""testing_grup_b.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xZKmnv-Jt-xVk161aZ4j6ReHgg0LhP9z

# **A/B Testing Rekomendasi Saham**

Pada project ini dilakukan A/B Testing untuk membandingkan dua metode rekomendasi saham dan melihat metode mana yang lebih sering menghasilkan rekomendasi yang sesuai dengan kondisi pasar sebagai bahan pertimbangan investor dalam mengambil keputusan.

### **Grup A**
Grup A menggunakan analisis teknikal dengan indikator:
- Relative Strength Index (RSI)
- Moving Average (MA)

Dari kedua indikator tersebut akan dihasilkan rekomendasi:
- Buy
- Sell
- Hold

Rekomendasi pada Grup A hanya berdasarkan pergerakan harga dan indikator teknikal saham.

### **Grup B**
Grup B menggunakan kombinasi:
- Relative Strength Index (RSI)
- Moving Average (MA)
- Analisis Sentimen Berita

Pada grup ini, rekomendasi teknikal dari RSI dan MA akan diperkuat atau diperlemah menggunakan sentimen berita finansial yang telah diklasifikasikan menjadi:
- Positif
- Netral
- Negatif

Dengan tambahan sentimen berita, rekomendasi diharapkan dapat lebih menggambarkan kondisi pasar secara umum.

### **Tujuan A/B Testing**
A/B Testing dilakukan untuk melihat:
- Metode mana yang lebih sering memberikan rekomendasi yang benar
- Pengaruh penambahan sentimen berita terhadap hasil rekomendasi
- Efektivitas analisis teknikal dibandingkan kombinasi teknikal dan sentimen

Pada notebook ini, pembahasan difokuskan pada pengerjaan Grup B.

# **Import Library**
"""

import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency
from scipy.stats import mannwhitneyu

"""# **Data Wrangling**

## **Data Gathering**
Mengumpulkan dan membaca data dari sumber yang tersedia:

- Load Dataset Grup A
- Load Dataset Berita
"""

# Load Dataset Grup A

df_grup_a = pd.read_csv('ab_testing_grup_a.csv')
print(df_grup_a.head())
print()
print('Shape:', df_grup_a.shape)
print()
print(df_grup_a.dtypes)

"""**Hasil:**

Dataset berisi hasil pengolahan indikator teknikal saham menggunakan RSI dan Moving Average (MA) untuk menghasilkan sinyal rekomendasi trading. Dataset memiliki total **42.976 data** dengan **8 kolom**.

Kolom `Final_Signal` menunjukkan sinyal akhir rekomendasi, sedangkan `Prediksi_Benar` digunakan untuk mengevaluasi apakah prediksi model sesuai atau tidak, dengan nilai:

- 1 = prediksi benar
- 0 = prediksi salah

Berdasarkan data yang ditampilkan, sebagian besar sinyal menghasilkan rekomendasi `Buy`, namun masih banyak prediksi yang bernilai 0, sehingga menunjukkan bahwa model belum mampu memberikan prediksi yang konsisten akurat.
"""

# Load Dataset Berita

df_berita = pd.read_csv('dataset_berita.csv')
print(df_berita.head())
print()
print('Shape:', df_berita.shape)
print()
print(df_berita.dtypes)

"""**Hasil:**

Dataset memiliki total 9.816 data dengan 4 kolom.

Penjelasan kolom:
- judul: judul berita
- tanggal: tanggal publikasi berita
- sentimen: label sentimen berita
- sentimen_encoded: hasil encoding sentimen dalam bentuk angka

Nilai pada sentimen_encoded:
- 0 = negatif
- 1 = netral
- 2 = positif

Berdasarkan data, sebagian besar berita memiliki sentimen netral. Dataset ini digunakan sebagai data input untuk analisis pengaruh sentimen berita terhadap rekomendasi saham.

## **Data Assessing**
Menilai kualitas dan struktur data sebelum dibersihkan:

- Cek missing values
- Cek duplikat
"""

# Cek Missing Values

print('Missing Values Grup A:')
print(df_grup_a.isnull().sum())
print()
print('Missing Values Dataset Berita:')
print(df_berita.isnull().sum())

"""**Hasil**

Tidak ada missing values di kedua dataset
- Grup A: 0 missing values di semua kolom
- Dataset Berita: 0 missing values di semua kolom

Data sudah bersih dan siap digunakan untuk tahap selanjutnya.
"""

# Cek Duplikat

print('Duplikat Grup A:', df_grup_a.duplicated().sum())
print('Duplikat Dataset Berita:', df_berita.duplicated().sum())

"""**Hasil:**

Ditemukan 1.102 duplikat di Grup A dan 0 duplikat di Dataset Berita.

## **Data Cleaning**
Pada tahap ini dilakukan pembersihan data berdasarkan hasil assessing, yaitu menghapus data duplikat pada dataset Grup A.
"""

# Hapus Duplikat Grup A

df_grup_a = df_grup_a.drop_duplicates()
print('Shape Grup A setelah hapus duplikat:', df_grup_a.shape)

"""**Hasil:**

- Sebelum: 42.976 baris
- Sesudah: 41.874 baris
- Terhapus: 1.102 baris duplikat

# **Eksplorasi Data Analisis (EDA)**
Pada tahap ini dilakukan untuk memahami struktur, distribusi, dan kondisi data sebelum diolah lebih lanjut. EDA membantu memastikan data yang digunakan sudah bersih, lengkap, dan siap untuk diproses ke tahap berikutnya.
"""

# Distribusi Final Signal Grup A

print('Distribusi Final Signal Grup A:')
print(df_grup_a['Final_Signal'].value_counts())
print()
print('Persentase:')
print(df_grup_a['Final_Signal'].value_counts(normalize=True).mul(100).round(2).astype(str) + '%')

"""**Hasil:**

Distribusi `Final_Signal` pada Grup A menunjukkan bahwa sebagian besar data menghasilkan sinyal `Buy` dan `Sell`.

Jumlah masing-masing sinyal:

- Buy sebanyak 23.010 data (54.95%)
- Sell sebanyak 18.838 data (44.99%)
- Strong Buy sebanyak 20 data (0.05%)
- Strong Sell sebanyak 6 data (0.01%)

Berdasarkan distribusi tersebut, sinyal `Buy` menjadi rekomendasi yang paling dominan pada dataset Grup A, sedangkan sinyal `Strong Buy` dan `Strong Sell` muncul dalam jumlah yang sangat sedikit.
"""

# Distribusi Sentimen Dataset Berita

print('Distribusi Sentimen Dataset Berita:')
print(df_berita['sentimen'].value_counts())
print()
print('Persentase:')
print(df_berita['sentimen'].value_counts(normalize=True).mul(100).round(2).astype(str) + '%')

"""**Hasil:**

Distribusi sentimen pada dataset berita menunjukkan bahwa sebagian besar berita memiliki sentimen netral.

Jumlah masing-masing sentimen:
- Netral: 4.354 (44.36%)
- Positif: 2.887 (29.41%)
- Negatif: 2.575 (26.23%)

Sentimen didominasi oleh netral, artinya sebagian besar berita finansial tidak condong ke arah positif maupun negatif. Distribusi inilah yang akan digunakan sebagai representasi kondisi pasar dalam simulasi Grup B.

# **Feature Engineering**
Pada tahap ini dilakukan penambahan fitur baru yaitu kolom Sentimen ke dalam dataset Grup A. Sentimen di-assign secara acak berdasarkan distribusi dari dataset berita (44.36% netral, 29.41% positif, 26.23% negatif).

Pendekatan ini digunakan karena A/B Testing yang dilakukan bersifat simulasi berbasis logika, bukan pencocokan data aktual. Tujuannya adalah untuk membuktikan secara statistik apakah penambahan sentimen berita memberikan pengaruh yang signifikan terhadap sinyal rekomendasi saham, bukan untuk menghasilkan prediksi real-time.
"""

# Assign Sentimen ke Dataset Grup A

np.random.seed(42)
df_grup_a['Sentimen'] = np.random.choice(
    ['netral', 'positif', 'negatif'],
    size=len(df_grup_a),
    p=[0.4436, 0.2941, 0.2623]
)

print(df_grup_a[['Stock Code', 'Last Trading Date', 'Final_Signal', 'Sentimen']].head(10))

"""**Hasil:**

Data tersebut menunjukkan hasil penggabungan antara sinyal saham `Final_Signal` dengan data sentimen berita `Sentimen` berdasarkan tanggal perdagangan.

Berdasarkan data, saham AALI didominasi oleh sinyal Buy, sementara sentimen berita yang muncul bervariasi antara netral, negatif, dan positif. Penggabungan data ini digunakan untuk menganalisis apakah sentimen berita dapat memengaruhi rekomendasi saham yang dihasilkan model.

# **Membangun Logika Grup B**
Pada tahap ini dibuat sinyal rekomendasi baru yaitu `Signal_B` dengan menggabungkan `Final_Signal` dari Grup A dan Sentimen dari dataset berita. Logika yang digunakan:

- Sinyal teknikal dan sentimen searah → sinyal diperkuat
- Sinyal teknikal dan sentimen berlawanan → sinyal diperlemah menjadi Hold
- Sentimen netral → sinyal tetap mengikuti teknikal
"""

# Buat Fungsi Logika Grup B

def logika_grup_b(final_signal, sentimen):
    if sentimen == 'positif':
        if final_signal in ['Buy', 'Strong Buy']:
            return 'Strong Buy'
        elif final_signal in ['Sell', 'Strong Sell']:
            return 'Hold'
    elif sentimen == 'negatif':
        if final_signal in ['Sell', 'Strong Sell']:
            return 'Strong Sell'
        elif final_signal in ['Buy', 'Strong Buy']:
            return 'Hold'
    return final_signal

df_grup_a['Signal_B'] = df_grup_a.apply(
    lambda row: logika_grup_b(row['Final_Signal'], row['Sentimen']), axis=1
)

print(df_grup_a[['Stock Code', 'Final_Signal', 'Sentimen', 'Signal_B']].head(10))

"""**Hasil:**

Data tersebut menunjukkan hasil rekomendasi pada Grup B setelah penambahan faktor sentimen berita ke dalam sinyal saham.

- Sentimen positif cenderung mengubah sinyal Buy menjadi Strong Buy
- Sentimen negatif cenderung mengubah sinyal Buy menjadi Hold
- Sentimen netral umumnya mempertahankan sinyal Buy

Hasil ini menunjukkan bahwa sentimen berita digunakan sebagai faktor penyesuaian untuk memperkuat, melemahkan, atau mempertahankan rekomendasi saham pada model Grup B.

- Buy + Netral → Buy (tetap)
- Buy + Negatif → Hold (diperlemah)
- Buy + Positif → Strong Buy (diperkuat)
"""

#  Cek Distribusi Signal_B

print('Distribusi Signal_B Grup B:')
print(df_grup_a['Signal_B'].value_counts())
print()
print('Persentase:')
print(df_grup_a['Signal_B'].value_counts(normalize=True).mul(100).round(2).astype(str) + '%')

"""**Hasil:**

Distribusi Signal_B pada Grup B menunjukkan variasi rekomendasi yang lebih beragam setelah penambahan faktor sentimen berita.

Jumlah masing-masing sinyal:

- Hold sebanyak 11.570 data (27.63%)
- Buy sebanyak 10.241 data (24.46%)
- Sell sebanyak 8.362 data (19.97%)
- Strong Buy sebanyak 6.798 data (16.23%)
- Strong Sell sebanyak 4.903 data (11.71%)

Berdasarkan distribusi tersebut, sinyal Hold menjadi rekomendasi yang paling dominan pada Grup B.

Selain itu, kemunculan sinyal **Strong Buy** dan **Strong Sell** meningkat dibandingkan Grup A, menunjukkan bahwa penambahan sentimen berita membuat hasil rekomendasi menjadi lebih dinamis dan variatif.

# **Menghitung Akurasi**
Pada tahap ini dihitung akurasi Grup A dan Grup B untuk dibandingkan. Untuk Grup B, sinyal Hold tidak dimasukkan ke dalam perhitungan akurasi karena Hold berarti tidak mengambil posisi transaksi.
"""

# Buat Ground Truth Grup B

def prediksi_benar_grup_b(signal_b, prediksi_benar_a):
    if signal_b == 'Hold':
        return 0
    return prediksi_benar_a

df_grup_a['Prediksi_Benar_B'] = df_grup_a.apply(
    lambda row: prediksi_benar_grup_b(row['Signal_B'], row['Prediksi_Benar']), axis=1
)

print(df_grup_a[['Final_Signal', 'Signal_B', 'Prediksi_Benar', 'Prediksi_Benar_B']].head(10))

"""**Hasil:**

Ground Truth pada Grup B berhasil dibuat dan menunjukkan bahwa logika evaluasi berjalan dengan benar, yaitu:

- Signal_B = Hold → Prediksi_Benar_B otomatis bernilai 0
- Signal_B = Buy atau Strong Buy → Prediksi_Benar_B mengikuti hasil Prediksi_Benar pada Grup A
"""

# Hitung Akurasi Grup A dan Grup B

akurasi_a = df_grup_a['Prediksi_Benar'].mean() * 100

df_grup_b_aktif = df_grup_a[df_grup_a['Signal_B'] != 'Hold']
akurasi_b = df_grup_b_aktif['Prediksi_Benar_B'].mean() * 100

print(f'Akurasi Grup A (RSI + MA): {akurasi_a:.2f}%')
print(f'Akurasi Grup B (RSI + MA + Sentimen): {akurasi_b:.2f}%')
print()
print(f'Jumlah data aktif Grup B (non-Hold): {len(df_grup_b_aktif)}')
print(f'Selisih Akurasi: {akurasi_b - akurasi_a:.2f}%')

"""**Hasil:**

- Akurasi Grup A (RSI + MA) sebesar 49.61%
- Akurasi Grup B (RSI + MA + Sentimen) sebesar 49.28%
- Jumlah data aktif Grup B (non-Hold) sebanyak 30.304 data
- Selisih akurasi sebesar -0.32%

Hasil tersebut menunjukkan bahwa penambahan sentimen berita belum meningkatkan akurasi model secara signifikan. Namun, karena perbedaannya sangat kecil, sehingga belum bisa disimpulkan apakah Grup B lebih baik atau tidak. Perlu dibuktikan dulu secara statistik apakah perbedaan ini signifikan atau hanya kebetulan.

# **Uji Statistik Chi-Square**

Pada tahap ini dilakukan uji statistik Chi-Square menggunakan `pd.crosstab` untuk membuktikan apakah penambahan komponen sentimen berita pada Grup B secara nyata mengubah pola distribusi sinyal rekomendasi jika dibandingkan dengan Grup A, atau pergeseran tersebut hanya terjadi karena kebetulan acak.
"""

# Bandingkan distribusi sinyal Grup A vs Grup B menggunakan crosstab
tabel_kontingensi = pd.crosstab(
    df_grup_a['Signal_B'],
    df_grup_a['Final_Signal']
)

print('Tabel Kontingensi Pergeseran Sinyal:')
print(tabel_kontingensi)
print()

# Jalankan uji statistik Chi-Square
chi2, p_value, dof, expected = chi2_contingency(tabel_kontingensi)

print(f'Chi-Square: {chi2:.4f}')
print(f'P-Value: {p_value:.4f}')
print(f'Degree of Freedom: {dof}')
print()

if p_value < 0.05:
    print('Hasil: Perbedaan signifikan ditemukan.')
    print('Penambahan sentimen berita terbukti mengubah pola distribusi sinyal rekomendasi.')
else:
    print('Hasil: Tidak ada perbedaan signifikan.')
    print('Perubahan sinyal rekomendasi tidak berbeda nyata secara statistik.')

"""**Hasil:**

- Chi-Square: 30273.0192
- P-Value: 0.0000
- Degree of Freedom: 12

Tabel kontingensi menunjukkan dengan jelas bagaimana sentimen berita mengubah pola sinyal rekomendasi:
- Buy dari Grup A → sebagian tetap Buy, sebagian berubah menjadi Hold atau Strong Buy
- Sell dari Grup A → sebagian tetap Sell, sebagian berubah menjadi Hold atau Strong Sell
- Tidak ada sinyal yang berpindah dari Buy ke Sell atau sebaliknya, yang membuktikan logika Grup B berjalan dengan benar

P-Value 0.0000 membuktikan bahwa perubahan pola sinyal ini bukan kebetulan melainkan pengaruh nyata dari penambahan sentimen berita.

# **Kesimpulan**
"""

print('HASIL A/B TESTING')
print()
print(f'Akurasi Grup A (RSI + MA)            : {akurasi_a:.2f}%')
print(f'Akurasi Grup B (RSI + MA + Sentimen) : {akurasi_b:.2f}%')
print(f'Selisih Akurasi                      : {akurasi_b - akurasi_a:.2f}%')
print()
print(f'Chi-Square : {chi2:.4f}')
print(f'P-Value    : {p_value:.4f}')
print()
if p_value < 0.05:
    print('Hasil: Perbedaan signifikan ditemukan.')
    print('Sentimen berita berpengaruh terhadap sinyal rekomendasi.')
else:
    print('Hasil: Tidak ada perbedaan signifikan.')

"""## **Kesimpulan A/B Testing**

Berdasarkan hasil pengujian, Grup A yang menggunakan indikator RSI dan Moving Average menghasilkan akurasi sebesar 49.61%, sedangkan Grup B yang menggunakan kombinasi RSI, MA, dan sentimen berita menghasilkan akurasi sebesar 49.28%. Akurasi Grup B lebih rendah dari Grup A dengan selisih sebesar 0.32%.
Namun, hasil uji Chi-Square menunjukkan nilai 30273.02 dengan P-Value 0.0000, yang membuktikan bahwa penambahan sentimen berita memberikan pengaruh yang signifikan secara statistik terhadap perubahan pola sinyal rekomendasi saham. Hal ini terlihat dari pergeseran sinyal Buy dan Sell menjadi Strong Buy, Strong Sell, maupun Hold tergantung kondisi sentimen berita yang berlaku.

Perlu dicatat bahwa sentimen yang digunakan pada pengujian ini masih berupa
simulasi berdasarkan distribusi dataset berita, bukan output model Deep
Learning yang sesungguhnya. Oleh karena itu, hasil akurasi Grup B belum
dapat dijadikan kesimpulan final dan akan diperbarui setelah model sentimen
dari AI Engineer selesai diintegrasikan.
"""

# Ekspor CSV

df_grup_a.to_csv('ab_testing_grup_b.csv', index=False)