# -*- coding: utf-8 -*-
"""AB_Testing_GroupA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pu_yqU_nv8etub5XCoAuVDIxk6hMFoKi

# **A/B Testing — Grup A (RSI + Moving Average Only)**

Notebook ini merupakan bagian dari proses A/B Testing pada proyek
**Anti FOMO Stock Mentor**.

### Tujuan
Mengukur seberapa akurat sinyal investasi saham yang dihasilkan hanya
dari indikator teknikal RSI dan Moving Average, tanpa bantuan sentimen berita.

### Mengapa Perlu A/B Testing?
Karena proyek ini ingin membuktikan bahwa menambahkan sentimen berita
ke dalam sistem rekomendasi saham benar-benar meningkatkan akurasi,
bukan hanya asumsi semata.

### Grup A vs Grup B
| | Grup A | Grup B |
|---|---|---|
| Pendekatan | RSI + MA saja | RSI + MA + Sentimen Berita |
| Dikerjakan oleh | Data Scientist 1 | Data Scientist 2 |
| Status | ✅ Notebook ini | ⏳ Menunggu model AI Engineer |

### Alur Notebook
1. Load data hasil olahan dari notebook Dataset Saham
2. Buat Ground Truth
3. Ukur akurasi sinyal
4. Uji statistik
5. Visualisasi
6. Simpan hasil untuk dibandingkan dengan Grup B

## **Tahap 1 — Install dan Import Library**

Sebelum memulai analisis, kita perlu memastikan semua library yang dibutuhkan
sudah tersedia dan siap digunakan.

Library yang digunakan pada notebook ini:
- **pandas** — untuk mengolah dan memanipulasi data dalam bentuk tabel
- **numpy** — untuk operasi matematika dan array
- **matplotlib & seaborn** — untuk membuat visualisasi grafik
- **scipy** — untuk melakukan uji statistik pada A/B Testing
- **warnings** — untuk menyembunyikan pesan peringatan yang tidak penting
"""

# Commented out IPython magic to ensure Python compatibility.
# Install jika belum ada
# %pip install scipy statsmodels

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

print("Library berhasil diimport!")

"""## **Tahap 2 — Load Data**

Data yang digunakan pada notebook ini adalah hasil olahan dari notebook
**Dataset Saham.ipynb** yang sudah melalui proses:
- Data Wrangling (Gathering, Assessing, Cleaning)
- Exploratory Data Analysis (EDA)
- Feature Engineering (perhitungan RSI dan Moving Average)

Data tersebut sudah disimpan dalam file `cleaned_stock_data.csv` yang
berada di folder `data`. File inilah yang kita load di sini sehingga
tidak perlu mengulang proses pengolahan data dari awal.

Kolom penting yang akan digunakan dalam A/B Testing:
| Kolom | Keterangan |
|---|---|
| `Stock Code` | Kode saham |
| `Last Trading Date` | Tanggal perdagangan |
| `Close` | Harga penutupan saham |
| `RSI` | Nilai indikator RSI |
| `RSI_Signal` | Sinyal dari RSI (Buy/Hold/Sell) |
| `MA_Crossover` | Sinyal crossover Moving Average |
| `Final_Signal` | Rekomendasi akhir gabungan RSI + MA |
"""

# Cek kolom yang tersedia
df_clean = pd.read_csv('../data/cleaned_stock_data.csv', parse_dates=['Last Trading Date'])
print("Data berhasil diload!")
print(df_clean.columns.tolist())
df_clean.head()

print(f"Jumlah baris : {df_clean.shape[0]:,}")
print(f"Jumlah kolom : {df_clean.shape[1]}")
print(f"Periode data : {df_clean['Last Trading Date'].min().date()} s/d {df_clean['Last Trading Date'].max().date()}")
print(f"Jumlah saham : {df_clean['Stock Code'].nunique()} saham")

"""Data berhasil diload dengan total **198.039 baris** dan **42 kolom**.
Pada tampilan di atas hanya ditampilkan 5 baris pertama sebagai preview
awal untuk memastikan data sudah terbaca dengan benar dan strukturnya sesuai.

Kolom-kolom penting seperti `RSI`, `RSI_Signal`, `MA_Crossover`, dan
`Final_Signal` sudah tersedia dan siap digunakan untuk proses A/B Testing.

Untuk 5 baris pertama yang ditampilkan, seluruhnya masih bernilai `Hold`
pada kolom `Final_Signal` karena berada di awal periode data dimana RSI
dan MA belum bisa dihitung (butuh minimal 14 hari untuk RSI dan 20 hari
untuk MA20). Nilai NaN pada kolom `MA5`, `MA20`, dan `RSI` di baris-baris
awal adalah hal yang wajar dan tidak perlu dikhawatirkan.
"""

# Cek duplikat di df_clean sebelum difilter
print("Duplikat di df_clean:", df_clean.duplicated().sum())

# Cek duplikat di df_signal setelah difilter
# Cek duplikat di df_clean sebelum difilter
print("Duplikat di df_clean:", df_clean.duplicated().sum())

# Cek duplikat di df_signal setelah difilter
df_signal_temp = df_clean[
    df_clean['Final_Signal'].isin(['Buy', 'Strong Buy', 'Sell', 'Strong Sell'])
].copy()
print("Duplikat di df_signal:", df_signal_temp.duplicated().sum())

# Lihat contoh baris yang duplikat
print(df_signal_temp[df_signal_temp.duplicated(keep=False)].sort_values(
    ['Stock Code', 'Last Trading Date']
).head(10))

# Hapus duplikat di df_clean
print("Jumlah data sebelum hapus duplikat:", len(df_clean))
df_clean = df_clean.drop_duplicates()
print("Jumlah data setelah hapus duplikat:", len(df_clean))

"""Ditemukan **698 duplikat** pada `df_clean` yang berasal dari dataset mentah
yang lolos dari proses cleaning sebelumnya. Duplikat ini terjadi karena
beberapa saham memiliki data perdagangan yang identik di semua kolom pada
tanggal yang sama, seperti yang ditemukan pada saham AKKU.

Setelah dilakukan penghapusan duplikat, jumlah data berkurang dari
sebelumnya. Proses ini dilakukan di tahap awal agar seluruh analisis
selanjutnya menggunakan data yang bersih dan tidak ada baris yang
terhitung dua kali.

## **Tahap 3 — Membuat Ground Truth**

Ground Truth adalah jawaban yang sebenarnya terjadi di pasar.
Karena kita ingin tahu apakah sinyal Buy/Sell dari RSI + MA itu benar,
maka kita perlu tahu apakah harga saham benar-benar naik atau turun
keesokan harinya setelah sinyal muncul.

- Kalau sinyal **Buy** → harga besok seharusnya **naik**
- Kalau sinyal **Sell** → harga besok seharusnya **turun**
"""

# Buat kolom harga keesokan hari per saham
df_clean['Close_Besok'] = df_clean.groupby('Stock Code')['Close'].shift(-1)

# Ground Truth: apakah harga besok benar-benar naik?
df_clean['Harga_Naik_Besok'] = (df_clean['Close_Besok'] > df_clean['Close']).astype(int)

# Cek hasilnya
print("Contoh Ground Truth:")
df_clean[['Stock Code', 'Last Trading Date', 'Close',
          'Close_Besok', 'Harga_Naik_Besok']].head(10)

"""**Ground Truth** berhasil dibuat. Kolom `Close_Besok` berisi harga penutupan
keesokan harinya, sedangkan `Harga_Naik_Besok` bernilai 1 jika harga besok
lebih tinggi dari hari ini, dan 0 jika sebaliknya.

Contoh membaca tabel:
- Baris ke-2 (2022-09-05): harga hari ini 9.025 → besok 9.075 → naik → nilai 1
- Baris ke-3 (2022-09-06): harga hari ini 9.075 → besok 9.000 → turun → nilai 0

Ground Truth inilah yang menjadi acuan untuk mengukur apakah setiap sinyal
Buy/Sell dari RSI + MA benar-benar terjadi di pasar.

## **Tahap 4 — Mengukur Akurasi Grup A (RSI + MA)**

Pada tahap ini kita mengukur seberapa sering sinyal dari RSI dan Moving Average
itu benar berdasarkan Ground Truth yang sudah dibuat sebelumnya.

Sinyal Hold tidak diikutkan dalam pengukuran karena Hold tidak memberikan
rekomendasi yang bisa diukur kebenarannya.
"""

# Ambil hanya baris yang ada sinyal Buy atau Sell (bukan Hold)
# karena Hold tidak bisa diukur akurasinya
df_signal = df_clean[
    df_clean['Final_Signal'].isin(['Buy', 'Strong Buy', 'Sell', 'Strong Sell'])
].copy().dropna(subset=['Close_Besok'])

# Cek apakah prediksi benar:
# Kalau sinyal Buy/Strong Buy → seharusnya harga naik besok
# Kalau sinyal Sell/Strong Sell → seharusnya harga turun besok
df_signal['Prediksi_Benar'] = (
    (df_signal['Final_Signal'].isin(['Buy', 'Strong Buy']) &
     (df_signal['Harga_Naik_Besok'] == 1)) |
    (df_signal['Final_Signal'].isin(['Sell', 'Strong Sell']) &
     (df_signal['Harga_Naik_Besok'] == 0))
).astype(int)

# Hitung akurasi keseluruhan Grup A
total_sinyal = len(df_signal)
total_benar  = df_signal['Prediksi_Benar'].sum()
akurasi_grup_a = total_benar / total_sinyal

print("=" * 45)
print("       HASIL GRUP A (RSI + MA Only)")
print("=" * 45)
print(f"Total sinyal Buy/Sell : {total_sinyal:,}")
print(f"Prediksi benar        : {total_benar:,}")
print(f"Akurasi Grup A        : {akurasi_grup_a:.2%}")
print("=" * 45)

"""- Dari total 43.383 sinyal Buy/Sell yang dihasilkan oleh RSI + MA, hanya
21.464 sinyal yang prediksinya benar, menghasilkan **akurasi sebesar 49.48%**.
- Akurasi ini hampir sama dengan tebak-tebakan acak (50%), yang berarti
**RSI + MA saja tidak cukup** untuk membuat rekomendasi investasi yang andal.

Temuan ini justru memperkuat alasan mengapa proyek Anti FOMO Stock Mentor
perlu menambahkan sentimen berita ke dalam sistem rekomendasinya, yang akan
diuji pada Grup B.

## **Tahap 5 — Breakdown Akurasi per Jenis Sinyal**

Selain akurasi keseluruhan, kita juga perlu melihat akurasi masing-masing
jenis sinyal secara terpisah, yaitu Buy, Strong Buy, Sell, dan Strong Sell.
Tujuannya untuk mengetahui jenis sinyal mana yang paling akurat dan mana
yang perlu diperbaiki.
"""

breakdown = df_signal.groupby('Final_Signal').agg(
    Total_Sinyal  = ('Prediksi_Benar', 'count'),
    Total_Benar   = ('Prediksi_Benar', 'sum')
).reset_index()

breakdown['Akurasi'] = (breakdown['Total_Benar'] / breakdown['Total_Sinyal'] * 100).round(2)
breakdown['Akurasi'] = breakdown['Akurasi'].astype(str) + '%'

print("\nBreakdown Akurasi per Jenis Sinyal:")
print(breakdown.to_string(index=False))

"""Terdapat perbedaan akurasi yang sangat signifikan antara sinyal `Sell` dan `Buy`:

- **Sell: 73.2%** — akurasi tinggi karena periode data Sep 2022–Okt 2023
  adalah periode bearish dimana pasar cenderung turun, sehingga sinyal jual
  lebih sering terbukti benar.
- **Buy: 30.03%** — akurasi rendah karena di pasar yang sedang turun,
  rekomendasi beli jarang berhasil. Harga yang disinyalkan akan naik justru
  sering melanjutkan penurunan.
- **Strong Buy & Strong Sell** memiliki jumlah data yang sangat sedikit
  (20 dan 6 sinyal) sehingga akurasinya belum bisa dijadikan patokan yang kuat.

**Kesimpulan:** Indikator teknikal RSI + MA sangat bergantung pada kondisi pasar.
Pada pasar bearish, sinyal Sell lebih dapat diandalkan, namun sinyal Buy justru
menjadi tidak akurat.

## **Tahap 6 — Akurasi per Saham**

Tidak semua saham berperilaku sama. Beberapa saham mungkin menghasilkan
sinyal yang lebih akurat dibanding saham lainnya tergantung karakteristik
pergerakan harganya. Pada tahap ini kita analisis akurasi sinyal per saham
untuk mengetahui saham mana yang paling cocok menggunakan pendekatan
RSI + Moving Average.

Hanya saham dengan minimal 10 sinyal yang diikutkan agar hasilnya
bermakna secara statistik.
"""

akurasi_per_saham = df_signal.groupby('Stock Code').agg(
    Total_Sinyal = ('Prediksi_Benar', 'count'),
    Total_Benar  = ('Prediksi_Benar', 'sum')
).reset_index()

akurasi_per_saham['Akurasi'] = (
    akurasi_per_saham['Total_Benar'] / akurasi_per_saham['Total_Sinyal']
)

# Filter saham dengan minimal 10 sinyal agar hasilnya bermakna
akurasi_per_saham = akurasi_per_saham[akurasi_per_saham['Total_Sinyal'] >= 10]

# Top 10 saham dengan akurasi tertinggi
top10 = akurasi_per_saham.nlargest(10, 'Akurasi')

print("Top 10 Saham dengan Akurasi Sinyal Tertinggi:")
top10['Akurasi_Pct'] = (top10['Akurasi'] * 100).round(2).astype(str) + '%'
print(top10[['Stock Code', 'Total_Sinyal', 'Total_Benar', 'Akurasi_Pct']].to_string(index=False))

# Cek detail sinyal untuk saham dengan akurasi 100%
saham_100 = top10['Stock Code'].tolist()

cek_detail = df_signal[df_signal['Stock Code'].isin(saham_100)].groupby(
    ['Stock Code', 'Final_Signal']
).size().reset_index(name='Jumlah')

print("Detail jenis sinyal pada saham dengan akurasi 100%:")
print(cek_detail.to_string(index=False))

"""Terdapat 10 saham dengan akurasi sinyal 100%, namun ini perlu dipahami
dengan hati-hati. Jika dilihat dari tabel, saham-saham seperti AKKU, ANDI,
BAPI, dan lainnya memiliki jumlah prediksi benar yang sama persis dengan
total sinyalnya, artinya seluruh sinyal yang dihasilkan untuk saham-saham
tersebut semuanya terbukti benar.

Hal ini kemungkinan besar terjadi karena periode data Sep 2022–Okt 2023
adalah periode bearish dimana pasar cenderung turun. Saham-saham dengan
akurasi 100% kemungkinan hanya menghasilkan sinyal `Sell` sepanjang periode,
dan karena pasar memang sedang turun, semua sinyal `Sell` tersebut kebetulan
terbukti benar.

Ini bukan berarti RSI + MA sempurna untuk saham-saham ini. Untuk
membuktikannya, kamu bisa cek lebih lanjut jenis sinyal apa saja yang
dihasilkan oleh saham-saham tersebut menggunakan kode di bawah ini:

## **Tahap 7 — Uji Statistik**

Akurasi saja tidak cukup untuk membuktikan bahwa sinyal RSI + MA benar-benar
bekerja. Bisa saja akurasi yang didapat hanyalah kebetulan semata.

Oleh karena itu kita lakukan uji statistik untuk membuktikan apakah
akurasi Grup A lebih baik secara signifikan dibanding tebak-tebakan acak
(baseline 50%).

- Jika **p-value < 0.05** → hasilnya signifikan, bukan kebetulan
- Jika **p-value ≥ 0.05** → hasilnya belum terbukti signifikan
"""

# Skor prediksi (1 = benar, 0 = salah)
skor_grup_a = df_signal['Prediksi_Benar'].values

# Baseline: random guess (akurasi 50%)
# Kita bandingkan apakah akurasi Grup A lebih baik dari tebak-tebakan
baseline = np.random.binomial(1, 0.5, size=len(skor_grup_a))

# Uji statistik
stat, p_value = stats.mannwhitneyu(skor_grup_a, baseline, alternative='greater')

print("\n" + "=" * 45)
print("         HASIL UJI STATISTIK")
print("=" * 45)
print(f"Akurasi Grup A   : {skor_grup_a.mean():.2%}")
print(f"Akurasi Baseline : {baseline.mean():.2%}")
print(f"P-value          : {p_value:.4f}")
print()
if p_value < 0.05:
    print("✅ Kesimpulan: Sinyal RSI + MA terbukti lebih")
    print("   baik dari tebak-tebakan secara statistik.")
else:
    print("❌ Kesimpulan: Sinyal RSI + MA belum terbukti")
    print("   lebih baik dari tebak-tebakan.")
print("=" * 45)

"""- Hasil uji statistik menunjukkan **p-value sebesar 0.9881**, jauh di atas
batas signifikansi 0.05. Artinya, akurasi Grup A **tidak terbukti lebih baik**
dari tebak-tebakan secara statistik.
- Ini berarti kita **gagal menolak H0**, yaitu tidak ada bukti bahwa sinyal
RSI + MA lebih baik dari random guess.

Temuan ini bukan berarti proyek gagal, justru sebaliknya. Hasil ini adalah
bukti ilmiah yang mendukung hipotesis proyek bahwa **RSI + MA saja tidak
cukup** dan perlu dikombinasikan dengan sentimen berita. Inilah yang akan
dibuktikan pada Grup B.

## **Tahap 8 — Visualisasi Hasil**

Hasil A/B Testing divisualisasikan dalam dua grafik:
1. **Akurasi per jenis sinyal** — untuk melihat jenis sinyal mana yang
   paling akurat
2. **Proporsi prediksi benar vs salah** — untuk melihat gambaran umum
   performa sinyal RSI + MA secara keseluruhan
"""

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# --- Grafik 1: Akurasi per Jenis Sinyal ---
sinyal_labels = df_signal.groupby('Final_Signal')['Prediksi_Benar'].mean() * 100
colors = ['green' if s in ['Buy', 'Strong Buy'] else 'red'
          for s in sinyal_labels.index]

axes[0].bar(sinyal_labels.index, sinyal_labels.values, color=colors, alpha=0.75)
axes[0].axhline(50, color='black', linestyle='--', linewidth=1, label='Baseline 50%')
axes[0].set_title('Akurasi per Jenis Sinyal\n(Grup A: RSI + MA Only)')
axes[0].set_ylabel('Akurasi (%)')
axes[0].set_ylim(0, 100)
axes[0].legend()
axes[0].grid(True, alpha=0.3, axis='y')
for i, v in enumerate(sinyal_labels.values):
    axes[0].text(i, v + 1, f'{v:.1f}%', ha='center', fontsize=10)

# --- Grafik 2: Distribusi Prediksi Benar vs Salah ---
benar_salah = df_signal['Prediksi_Benar'].value_counts()
axes[1].pie(
    benar_salah.values,
    labels=['Prediksi Benar', 'Prediksi Salah'],
    colors=['#2ecc71', '#e74c3c'],
    autopct='%1.1f%%',
    startangle=90
)
axes[1].set_title(f'Proporsi Prediksi Benar vs Salah\n(Grup A — Total {total_sinyal:,} sinyal)')

plt.suptitle('A/B Testing Grup A — RSI + Moving Average',
             fontsize=13, fontweight='bold')
plt.tight_layout()
plt.savefig('ab_testing_grup_a.png', dpi=150, bbox_inches='tight')
plt.show()

print("\nGrafik berhasil disimpan sebagai 'ab_testing_grup_a.png'")

"""Dari dua grafik yang dihasilkan:

1. **Grafik Akurasi per Jenis Sinyal**, terlihat jelas bahwa sinyal Sell
   berada jauh di atas garis baseline 50%, sedangkan sinyal Buy berada jauh
   di bawahnya. Ini memperlihatkan ketidakseimbangan performa yang sangat
   bergantung pada arah pasar.

2. **Grafik Proporsi Prediksi**, hampir 50:50 antara prediksi benar dan
   salah secara keseluruhan, memvisualkan bahwa RSI + MA tidak lebih baik
   dari tebak-tebakan acak bila diukur secara keseluruhan.

## **Tahap 9 — Simpan Hasil**

Hasil A/B Testing Grup A disimpan ke dalam file CSV agar nantinya bisa
dibandingkan dengan hasil Grup B yang menggunakan RSI + MA + Sentimen Berita.
Perbandingan antara Grup A dan Grup B inilah yang menjadi kesimpulan akhir
dari A/B Testing di proyek ini.
"""

# Cek duplikat sebelum simpan
print("Duplikat di df_signal sebelum simpan:", df_signal.duplicated().sum())

# Simpan skor Grup A ke CSV
df_signal = df_signal.drop_duplicates()
print("Jumlah data setelah hapus duplikat:", len(df_signal))

df_signal[['Stock Code', 'Last Trading Date', 'Close',
           'RSI', 'RSI_Signal', 'MA_Crossover',
           'Final_Signal', 'Prediksi_Benar']].to_csv(
    'ab_testing_grup_a.csv', index=False
)

print("File berhasil disimpan!")

"""Pengecekan duplikat dilakukan kembali sebelum file disimpan sebagai
lapisan pengaman kedua. Tujuannya untuk memastikan file `ab_testing_grup_a.csv`
yang akan diberikan kepada Data Scientist 2 untuk pengerjaan Grup B
benar-benar bebas dari data duplikat.

Dengan data yang sudah bersih, perbandingan antara Grup A dan Grup B
nantinya akan lebih adil karena keduanya menggunakan jumlah data
yang sama dan tidak ada baris yang terhitung lebih dari satu kali.
"""

# Simpan skor Grup A ke CSV agar bisa dibandingkan nanti
df_signal[['Stock Code', 'Last Trading Date', 'Close',
           'RSI', 'RSI_Signal', 'MA_Crossover',
           'Final_Signal', 'Prediksi_Benar']].to_csv(
    'ab_testing_grup_a.csv', index=False
)

# Simpan ringkasan hasil
ringkasan_a = {
    'Grup'          : 'A (RSI + MA Only)',
    'Total Sinyal'  : total_sinyal,
    'Total Benar'   : int(total_benar),
    'Akurasi'       : f'{akurasi_grup_a:.2%}',
    'P-value'       : round(p_value, 4),
    'Signifikan'    : p_value < 0.05
}

print("\nRingkasan Grup A disimpan:")
for k, v in ringkasan_a.items():
    print(f"  {k:15}: {v}")

print("\nFile 'ab_testing_grup_a.csv' berhasil disimpan!")
print("File ini akan digunakan untuk perbandingan dengan Grup B nanti.")

"""
Hasil A/B Testing Grup A telah berhasil disimpan ke dalam file
`ab_testing_grup_a.csv`. File ini berisi detail setiap sinyal beserta
hasil prediksinya, dan akan digunakan sebagai pembanding ketika Grup B
selesai dikerjakan oleh Data Scientist 2.

**Ringkasan Hasil Grup A:**
| Metrik | Nilai |
|---|---|
| Total Sinyal | 43.383 |
| Prediksi Benar | 21.464 |
| Akurasi | 49.48% |
| P-value | 0.9881 |
| Signifikan? | Tidak |

**Kesimpulan akhir Grup A:** Sinyal investasi yang hanya mengandalkan RSI
dan Moving Average tidak cukup untuk menghasilkan rekomendasi yang akurat.
Dibutuhkan tambahan informasi dari sentimen berita untuk meningkatkan
kualitas rekomendasi, yang akan dibuktikan pada Grup B."""